# Properties file for local/dev environment
# You need to configure the environment variable in your IDE, more info in README.md
# Overrides application.yml default properties

# LOCAL

#spring:
#  datasource:
#   driverClassName: com.mysql.cj.jdbc.Driver
#   url: jdbc:mysql://localhost:3306/warehouse?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
#   username: root
#   password: manuel86
#  jpa:
#    show-sql: true
#    generate-ddl: true
#    defer-datasource-initialization: true
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    hibernate:
#      ddl-auto: create-drop

#DATABASE

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASS}
    url: jdbc:mysql://${DB_HOST}/${SCHEMA_NAME}?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop


#jpa:
#  show-sql: true
#  database-platform: org.hibernate.dialect.MySQL8Dialect
#  defer-datasource-initialization: true
#  generate-ddl: true
#  hibernate:
#    ddl-auto: none